// @ts-nocheck
export const metiers = ["bucheron", "alchimiste", "paysan", "mineur", "pêcheur"];

export const getRessourceById = (id: string | number) => {
    return ressources.find((res) => res.id === String(id));
};

export const ressources = [
    {
        id: "36",
        name: "Ortie",
        backgroundPosition: "0px 0px",
        metier: "alchimiste",
    },
    {
        id: "37",
        name: "Sauge",
        backgroundPosition: "-52px 0px",
        metier: "alchimiste",
    },
    {
        id: "38",
        name: "Trèfle à 5 feuilles",
        backgroundPosition: "-104px 0px",
        metier: "alchimiste",
    },
    {
        id: "39",
        name: "Menthe Sauvage",
        backgroundPosition: "-156px 0px",
        metier: "alchimiste",
    },
    {
        id: "40",
        name: "Orchidée Freyesque",
        backgroundPosition: "-208px 0px",
        metier: "alchimiste",
    },
    {
        id: "80",
        name: "Edelweiss",
        backgroundPosition: "-260px 0px",
        metier: "alchimiste",
    },
    {
        id: "41",
        name: "Graine de Pandouille",
        backgroundPosition: "-312px 0px",
        metier: "alchimiste",
    },
    {
        id: "42",
        name: "Ginseng",
        backgroundPosition: "-364px 0px",
        metier: "alchimiste",
    },
    {
        id: "43",
        name: "Belladone",
        backgroundPosition: "-416px 0px",
        metier: "alchimiste",
    },
    {
        id: "44",
        name: "Mandragore",
        backgroundPosition: "-468px 0px",
        metier: "alchimiste",
    },
    {
        id: "45",
        name: "Perce-neige",
        backgroundPosition: "-520px 0px",
        metier: "alchimiste",
    },
    {
        id: "46",
        name: "Salikrone",
        backgroundPosition: "-780px 0px",
        metier: "alchimiste",
    },
    {
        id: "47",
        name: "Frêne",
        backgroundPosition: "-572px 0px",
        metier: "bucheron",
    },
    {
        id: "48",
        name: "Châtaignier",
        backgroundPosition: "-624px 0px",
        metier: "bucheron",
    },
    {
        id: "49",
        name: "Noyer",
        backgroundPosition: "-676px 0px",
        metier: "bucheron",
    },
    {
        id: "50",
        name: "Chêne",
        backgroundPosition: "-728px 0px",
        metier: "bucheron",
    },
    {
        id: "51",
        name: "Bombu",
        backgroundPosition: "0px -52px",
        metier: "bucheron",
    },
    {
        id: "52",
        name: "Erable",
        backgroundPosition: "-52px -52px",
        metier: "bucheron",
    },
    {
        id: "53",
        name: "Oliviolet",
        backgroundPosition: "-104px -52px",
        metier: "bucheron",
    },
    {
        id: "54",
        name: "If",
        backgroundPosition: "-156px -52px",
        metier: "bucheron",
    },
    {
        id: "55",
        name: "Bambou",
        backgroundPosition: "-208px -52px",
        metier: "bucheron",
    },
    {
        id: "56",
        name: "Merisier",
        backgroundPosition: "-260px -52px",
        metier: "bucheron",
    },
    {
        id: "57",
        name: "Noisetier",
        backgroundPosition: "-312px -52px",
        metier: "bucheron",
    },
    {
        id: "58",
        name: "Ebène",
        backgroundPosition: "-364px -52px",
        metier: "bucheron",
    },
    {
        id: "59",
        name: "Kaliptus",
        backgroundPosition: "-416px -52px",
        metier: "bucheron",
    },
    {
        id: "60",
        name: "Charme",
        backgroundPosition: "-468px -52px",
        metier: "bucheron",
    },
    {
        id: "61",
        name: "Bambou sombre",
        backgroundPosition: "-520px -52px",
        metier: "bucheron",
    },
    {
        id: "62",
        name: "Orme",
        backgroundPosition: "-572px -52px",
        metier: "bucheron",
    },
    {
        id: "63",
        name: "Bambou sacré",
        backgroundPosition: "-624px -52px",
        metier: "bucheron",
    },
    {
        id: "64",
        name: "Tremble",
        backgroundPosition: "-676px -52px",
        metier: "bucheron",
    },
    {
        id: "65",
        name: "Aquajou",
        backgroundPosition: "-780px -52px",
        metier: "bucheron",
    },
    {
        id: "68",
        name: "Fer",
        backgroundPosition: "-728px -52px",
        metier: "mineur",
    },
    {
        id: "67",
        name: "Cuivre",
        backgroundPosition: "0px -104px",
        metier: "mineur",
    },
    {
        id: "69",
        name: "Bronze",
        backgroundPosition: "-52px -104px",
        metier: "mineur",
    },
    {
        id: "70",
        name: "Kobalte",
        backgroundPosition: "-104px -104px",
        metier: "mineur",
    },
    {
        id: "71",
        name: "Manganèse",
        backgroundPosition: "-156px -104px",
        metier: "mineur",
    },
    {
        id: "72",
        name: "Etain",
        backgroundPosition: "-208px -104px",
        metier: "mineur",
    },
    {
        id: "73",
        name: "Silicate",
        backgroundPosition: "-260px -104px",
        metier: "mineur",
    },
    {
        id: "74",
        name: "Argent",
        backgroundPosition: "-312px -104px",
        metier: "mineur",
    },
    {
        id: "75",
        name: "Bauxite",
        backgroundPosition: "-364px -104px",
        metier: "mineur",
    },
    {
        id: "76",
        name: "Or",
        backgroundPosition: "-416px -104px",
        metier: "mineur",
    },
    {
        id: "77",
        name: "Dolomite",
        backgroundPosition: "-468px -104px",
        metier: "mineur",
    },
    {
        id: "78",
        name: "Obsidienne",
        backgroundPosition: "-520px -104px",
        metier: "mineur",
    },
    {
        id: "79",
        name: "Écume de mer",
        backgroundPosition: "-780px -104px",
        metier: "mineur",
    },
    {
        id: "23",
        name: "Blé",
        backgroundPosition: "-572px -104px",
        metier: "paysan",
    },
    {
        id: "24",
        name: "Orge",
        backgroundPosition: "-624px -104px",
        metier: "paysan",
    },
    {
        id: "25",
        name: "Avoine",
        backgroundPosition: "-676px -104px",
        metier: "paysan",
    },
    {
        id: "26",
        name: "Houblon",
        backgroundPosition: "-728px -104px",
        metier: "paysan",
    },
    {
        id: "27",
        name: "Lin",
        backgroundPosition: "0px -156px",
        metier: "paysan",
    },
    {
        id: "28",
        name: "Seigle",
        backgroundPosition: "-52px -156px",
        metier: "paysan",
    },
    {
        id: "29",
        name: "Riz",
        backgroundPosition: "-104px -156px",
        metier: "paysan",
    },
    {
        id: "30",
        name: "Malt",
        backgroundPosition: "-156px -156px",
        metier: "paysan",
    },
    {
        id: "31",
        name: "Chanvre",
        backgroundPosition: "-208px -156px",
        metier: "paysan",
    },
    {
        id: "32",
        name: "Maïs",
        backgroundPosition: "-260px -156px",
        metier: "paysan",
    },
    {
        id: "33",
        name: "Millet",
        backgroundPosition: "-312px -156px",
        metier: "paysan",
    },
    {
        id: "34",
        name: "Frostiz",
        backgroundPosition: "-364px -156px",
        metier: "paysan",
    },
    {
        id: "35",
        name: "Quisnoa",
        backgroundPosition: "-780px 0px",
        metier: "paysan",
    },
    {
        id: "1",
        name: "Goujon",
        backgroundPosition: "-416px -156px",
        metier: "pêcheur",
    },
    {
        id: "2",
        name: "Greuvette",
        backgroundPosition: "-468px -156px",
        metier: "pêcheur",
    },
    {
        id: "3",
        name: "Truite",
        backgroundPosition: "-520px -156px",
        metier: "pêcheur",
    },
    {
        id: "4",
        name: "Crabe",
        backgroundPosition: "-572px -156px",
        metier: "pêcheur",
    },
    {
        id: "5",
        name: "Poisson-Chaton",
        backgroundPosition: "-624px -156px",
        metier: "pêcheur",
    },
    {
        id: "6",
        name: "Poisson Pané",
        backgroundPosition: "-676px -156px",
        metier: "pêcheur",
    },
    {
        id: "7",
        name: "Carpe d'Iem",
        backgroundPosition: "-728px -156px",
        metier: "pêcheur",
    },
    {
        id: "8",
        name: "Sardine Brillante",
        backgroundPosition: "0px -208px",
        metier: "pêcheur",
    },
    {
        id: "9",
        name: "Brochet",
        backgroundPosition: "-52px -208px",
        metier: "pêcheur",
    },
    {
        id: "10",
        name: "Kralamoure",
        backgroundPosition: "-104px -208px",
        metier: "pêcheur",
    },
    {
        id: "11",
        name: "Anguille",
        backgroundPosition: "-156px -208px",
        metier: "pêcheur",
    },
    {
        id: "12",
        name: "Dorade Grise",
        backgroundPosition: "-208px -208px",
        metier: "pêcheur",
    },
    {
        id: "13",
        name: "Perche",
        backgroundPosition: "-260px -208px",
        metier: "pêcheur",
    },
    {
        id: "14",
        name: "Raie",
        backgroundPosition: "-312px -208px",
        metier: "pêcheur",
    },
    {
        id: "15",
        name: "Lotte",
        backgroundPosition: "-364px -208px",
        metier: "pêcheur",
    },
    {
        id: "16",
        name: "Requin Marteau-Faucille",
        backgroundPosition: "-416px -208px",
        metier: "pêcheur",
    },
    {
        id: "17",
        name: "Bar Rikain",
        backgroundPosition: "-468px -208px",
        metier: "pêcheur",
    },
    {
        id: "18",
        name: "Morue",
        backgroundPosition: "-520px -208px",
        metier: "pêcheur",
    },
    {
        id: "19",
        name: "Tanche",
        backgroundPosition: "-572px -208px",
        metier: "pêcheur",
    },
    {
        id: "20",
        name: "Espadon",
        backgroundPosition: "-624px -208px",
        metier: "pêcheur",
    },
    {
        id: "21",
        name: "Poisskaille",
        backgroundPosition: "-676px -208px",
        metier: "pêcheur",
    },
    {
        id: "22",
        name: "Patelle",
        backgroundPosition: "-780px -208px",
        metier: "pêcheur",
    },
    {
        id: "66",
        name: "Eau Potable",
        backgroundPosition: "-728px -208px",
        metier: "pêcheur",
    },
];
